version: "3.8"

# variables are read from .env

services:
  app:
    image: tomjtoth/veripalvelu
    build: .
    volumes:
      - ./.env:/usr/src/app/.env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

    # uncomment when deployed directly
    # ports:
    #   - ${APP_PORT}:80

  db:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
      - ./src/schema.sql:/docker-entrypoint-initdb.d/vp.sql
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
      timeout: 1s
      start_period: 5s
      start_interval: 100ms
    restart: unless-stopped

    # uncomment for local dev
    # ports:
    #   - 5432:5432
